---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: gathering-surf-cache-freshner
spec:
  schedule: "*/3 * * * *"
  jobTemplate:
    spec:
      backoffLimit: 5
      ttlSecondsAfterFinished: 300
      template:
        spec:
          containers:
            - name: gathering-surf-cache-freshner
              image: alpine
              command: ["sh", "-c"]
              args:
                - |
                  apk add --no-cache curl && \
                  curl -H 'host:gathering.surf' http://gathering-surf-server:8080 > /dev/null
          restartPolicy: OnFailure
